cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

cask 'xquartz'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'youtube-dl'

cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'steam'
cask 'utorrent'
cask 'vlc'
