cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-versions'

brew 'php72'
brew 'ack'
brew 'composer'
brew 'coreutils'
brew 'git-flow'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'redis'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'wget'
brew 'unrar'
brew 'gpg2'
brew 'qt'
brew 'mysql'
brew 'nginx'
brew 'nvm'
brew 'postgresql'
brew 'yarn'
brew 'bat'
brew 'jed'
brew 'mas'
brew 'gnupg'

mas 'Pixelmator', id: 407963104
mas 'Pocket', id: 568494494
mas 'Slack', id: 803453959
mas 'Spark', id: 1176895641
mas 'Telegram', id: 747648890
mas 'Tweetbot', id: 1384080005
mas 'Whatsapp', id: 1147396723
mas 'Xcode', id: 497799835
mas 'Todoist', id: 585829637

cask 'appcleaner'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'java'
cask 'spotify'
cask 'sequel-pro'
cask 'visual-studio-code'
cask 'vlc'
cask 'alfred'
cask 'caffeine'
cask 'dash'
cask 'tower2'
cask 'enpass'
cask 'spotify'
cask 'fantastical'
cask 'notion'
cask 'psequel'
cask 'discord'
cask 'xquartz'
cask 'apptivate'
cask 'bartender'
cask 'dropshare'
cask 'evernote'
cask 'keybase'
cask 'numi'
cask 'onedrive'
cask 'paw'
cask 'transmit'
cask 'divvy'
cask 'iterm2'
cask 'google-chrome-canary'
cask 'caskroom/fonts/font-hack'
cask 'caskroom/fonts/font-iosevka'
